name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install truffle -g
          npm install

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: lint
        run: npm run lint
      - name: solhint
        run: npm run solhint
      - name: format
        run: npm run prettier:check

  setup-node:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: run node
        run: truffle develop

  contract-test:
    runs-on: ubuntu-latest
    needs: [setup, check]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: check for port
        run: |
          while netstat -lnt; do
          awk '$4 ~ /:9545/ {exit 1}'
          sleep 5
          done
      - name: test
        run: truffle test
      - name: kill node
        run: kill $(lsof -t -i:9545)
